package com.synapsenet.core.event;

public enum EventType {
    TASK_CREATED,
    TASK_ASSIGNED,
    TASK_COMPLETED,
    AGENT_RESULT_PRODUCED,
    PLAN_PRODUCED, 
    CRITIC_FEEDBACK_PRODUCED,
    
    TASK_EXECUTED,
    TASK_BLOCKED,
    
    MEDIATION_APPROVED,
    MEDIATION_REJECTED,
    MEDIATION_REPLAN_REQUESTED
}
