spring.application.name=synapsenet
spring.profiles.active=ollama
server.port=8080
spring.main.web-application-type=servlet

synapsenet.workspace.path=/Users/dhruvsarda/Downloads/BugFile
synapsenet.python.executable=/Users/dhruvsarda/Downloads/BugFile/.venv/bin/python

# Ollama
ollama.base-url=http://localhost:11434
ollama.model=qwen2.5:14b-instruct